[package]
name = "kpick"
version = "0.1.0"
edition = "2021"

[dependencies]
# UI
smithay-client-toolkit = { version = "0.19", default-features = false, features = ["calloop", "xkbcommon"] }
fontdue = "0.9"
wayland-client = "0.31"

# Database
keepass = "0.8"
rpassword = "7.3"

# Core
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
nucleo-matcher = "0.3"
directories = "5.0"
dirs = "5"
thiserror = "2.0"
